Octadesk-Tech/chat-bot-builder-client

apps/builder/next.config.js

Test to fix builder in nextJS to QA

fix problem builder next

---

apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/SettingsPopoverContent.tsx

- Increase width in webhook's body modal

feat:adjust modal body in webhook component

---

apps/builder/components/shared/Graph/Nodes/StepNode/TextBubbleEditor/ToolBar.tsx

- Create a simple emoji menu for text editor

feat:emoji menu

---

apps/builder/assets/OctaDivider.tsx
apps/builder/assets/icons.tsx
apps/builder/components/octaComponents/OctaDivider/OctaDivider.tsx
apps/builder/components/octaComponents/OctaTooltip/OctaTooltip.tsx
apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeList/ItemNodesList.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/InputMediaSettingsBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/StepNode/StepNode.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/AssignToTeam/AssignToTeamContent.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/Input/InputContent.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/InputItemsContent/InputItemsContent.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/MediaInput/MediaInputContent.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/OctaCommerceContent/OctaCommerceContent.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/PreReserve/PreReserveContent.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WhatsApp/WhatsAppButtons/WhatsAppButtonsContent.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WhatsApp/WhatsAppOptions/WhatsAppOptionsContent.tsx
apps/builder/components/shared/ImageUploadContent/ImageUploadContent.tsx
apps/builder/components/shared/buttons/UploadButton.tsx
packages/models/src/typebot/steps/bubble.ts

Fixing bugs caught on upload component
Local and qas

fix: upload bugs

---

apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/MediaInput/MediaInputContent.tsx
apps/builder/components/shared/buttons/UploadButton.tsx

Little detail to complete the upload component fix
Local and qas

fix: max size error

---

apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WebhookSettings/KeyValueInputs.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WebhookSettings/WebhookSettings.tsx
apps/builder/components/shared/TableList.tsx

Variable select was getting under the next panel
Local and qas

fix: variable over accordion panel for webhook component

---

apps/builder/components/shared/Graph/Endpoints/SourceEndpoint.tsx
apps/builder/components/shared/Graph/Nodes/BlockNode/BlockNode.tsx

Whenever the user dragged a component or a connection on the bot tree, the text on other components were being selected, this PR fixes that.
Fixes # [(issue)](https://octadesk1614602251.atlassian.net/browse/OCTA-5507)
QA

fix: drag and drop text select

---

apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WebhookSettings/KeyValueInputs.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/StepNode/StepNode.tsx
apps/builder/components/shared/TableList.tsx

https://octadesk1614602251.atlassian.net/browse/OCTA-5972
https://octadesk1614602251.atlassian.net/browse/OCTA-5968
QA

fix: some bugs

---

README.md
apps/builder/.env.production.example
apps/builder/components/shared/CodeEditor.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WebhookSettings/OpenEditorBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WebhookSettings/WebhookSettings.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WhatsAppBodies/WhatsAppOptionsListSettings/WhatsAppOptionsListSettingsBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/TextBubbleEditor/TextBubbleEditor.tsx
apps/builder/components/shared/VariableSearchInput/VariableSearchInput.tsx
apps/builder/libs/theme.ts
apps/builder/package.json
apps/builder/pages/typebots.tsx
apps/docs/docs/self-hosting/docker.mdx
docker-compose.build.yml
docker-compose.yml

Permitindo inserir variáveis do editor JSON do Super Integrações
<kbd>![0002](https://github.com/Octadesk-Tech/chat-bot-builder-client/assets/2975926/ec0d0ad8-3e9b-4cac-ab95-e72b0c306b24)</kbd>
Lista de bots na tela inicial do app para não precisar montar a URL de edição na mão
<kbd>![0001](https://github.com/Octadesk-Tech/chat-bot-builder-client/assets/2975926/a33ea3df-daa8-433c-b88d-27e3f548ffc6)</kbd>
QA

fix: api integration variables list

---

apps/builder/components/shared/Graph/Nodes/StepNode/StepNode/StepNode.tsx

**Test Configuration**:
- Hardware:
- Toolchain:
- SDK:

fix: remove mouse enter and code smell

---

apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/WhatsAppButtonsContent/WhatsAppButtonsNodeContent.tsx
apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/WhatsAppOptionsContent/WhatsAppOptionsNodeContent.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WhatsAppBodies/WhatsAppButtonsListSettings/WhatsAppButtonsListSettingsBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WhatsAppBodies/WhatsAppOptionsListSettings/WhatsAppOptionsListSettingsBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/TextBubbleEditor/TextBubbleEditor.tsx

**Test Configuration**:
- Hardware:
- Toolchain:
- SDK:

fix: add max length in bubble editor

---

apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/WhatsAppOptionsContent/WhatsAppOptionsNodeContent.tsx

**Test Configuration**:
- Hardware:
- Toolchain:
- SDK:

Subida correção seleção de texto nos botões Whatsapp

---

apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ConditionSettingsBody/ComparisonsItem.tsx

**Test Configuration**:
- Hardware:
- Toolchain:
- SDK:

 Botão excluir nos itens da lista (Valide uma informação)

---

apps/builder/contexts/WorkspaceContext.tsx

Do not let variables with the same token as the default ones.
Local and qas

fix: do not add variable with same token as default

---

apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ConditionSettingsBody/ComparisonsItem.tsx

Inserção do botão de exclusão no item e remoção do botão na parte superior do modal do componente valide uma informação.
OCTA-7937
Testado em ambiente de QA, validado pelo Dev e QA.

Subida correão erro iconTrash

---

apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/AssignToTeam/AssignToTeamSettingsBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/StepNode/StepNode.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/AssignToTeam/AssignToTeamContent.tsx
packages/models/src/typebot/steps/octaStep.ts

When check availability of agents, we need to connect to another component.
Local and qas

fix: logic for check availability

---

apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ConditionSettingsBody/ComparisonsItem.tsx

Consider text as string for comparisson type.
Local and qas

fix: add text type to string comparators

---

packages/models/src/typebot/steps/octaStep.ts

Direcionar conversa vem com "switch" desativado
Dev + PM

feat: it sets isAvaible false as default value

---

apps/builder/components/shared/Graph/Nodes/StepNode/StepNode/StepNode.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/StepNodesList.tsx
apps/builder/helpers/block-connections.ts

Essa feature refatora o código do lista de pendências como também faz com que agora valide **blocos** com **múltiplos** passos
Dev + PM

feat: it adds validations when grouping multiple components

---

apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/SettingsPopoverContent.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/AssignToTeam/AssignToResponsibleSelect.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/AssignToTeam/AssignToTeamSettingsBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WebhookSettings/WebhookSettings.tsx

https://octadesk1614602251.atlassian.net/browse/OCTA-7301

feat: it replicates logical from v1 to select responsible for contact

---

apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/SettingsModal.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/TextBubbleEditor/TextBubbleEditor.tsx

https://octadesk1614602251.atlassian.net/browse/OCTA-7780
Dev + PM + designer

fix: it adjusts border fields on focus. It sets max height on dialogs

---

apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ChoiceInputSettingsBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WhatsAppBodies/WhatsAppButtonsListSettings/WhatsAppButtonsListSettingsBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WhatsAppBodies/WhatsAppOptionsListSettings/WhatsAppOptionsListSettingsBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WhatsApp/WhatsAppButtons/WhatsAppButtonsContent.tsx
apps/builder/components/shared/Graph/Nodes/helpers/helpers.tsx
apps/builder/contexts/TypebotContext/actions/steps.ts
packages/models/src/typebot/steps/inputs.ts
packages/models/src/typebot/steps/octaStep.ts

https://octadesk1614602251.atlassian.net/browse/SBOT-58

feat: it adds fallback messages to some components

---

apps/builder/components/shared/VariableSearchInput/VariableSearchInput.tsx
apps/builder/contexts/WorkspaceContext.tsx

Fix created return variable
Fixes #SBOT-70

fix: created return variable

---

apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ChoiceInputSettingsBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/InputSettingsBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WhatsAppBodies/WhatsAppButtonsListSettings/WhatsAppButtonsListSettingsBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WhatsAppBodies/WhatsAppOptionsListSettings/WhatsAppOptionsListSettingsBody.tsx
apps/builder/libs/theme.ts

[SBOT-78](https://octadesk1614602251.atlassian.net/browse/SBOT-78)
Consult [this](https://www.notion.so/octatech/Conven-o-de-Commits-6e9ddde2c4e44cdc9c50e7a0ef42b18c#b34b7041baa24ed28d422cb20de9e744) readme and set the correspondent label(s) on PR.
[SBOT-78]: https://octadesk1614602251.atlassian.net/browse/SBOT-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: it adds redirect after 3 attemps and collapse

---

apps/builder/services/octadesk/fileUploader/fileUploader.ts

fix: upload bot
Fixes #SBOT-90

fix: upload bot

---

apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/MediaInput/MediaInputContent.tsx

[SBOT-102](https://octadesk1614602251.atlassian.net/browse/SBOT-102)
[SBOT-102]: https://octadesk1614602251.atlassian.net/browse/SBOT-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: it adjusts css to uploaded file name size

---

apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/AssignToTeam/AssignToTeamSettingsBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/StepNode/StepNode.tsx

[OCTA-8573](https://octadesk1614602251.atlassian.net/browse/OCTA-8573)
[OCTA-8573]: https://octadesk1614602251.atlassian.net/browse/OCTA-8573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: it sets id to dialog and changes how the input is rendered

---

apps/builder/components/octaComponents/OctaSelect/OctaSelect.tsx
apps/builder/contexts/TypebotContext/TypebotContext.tsx

Corrigir as dependencias dentro do useMemo para que o bot renderize corretamente. Também irá tratar o erro no octaSelect para que a tela não "crash".

add dependencies inside useMemo

---

apps/builder/components/octaComponents/OctaSelect/OctaSelect.style.ts
apps/builder/components/octaComponents/OctaSelect/OctaSelect.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ConversationTag/ConversationTagSelect.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WebhookSettings/VariableForTestInputs.tsx
apps/builder/components/shared/VariableSearchInput/VariableSearchInput.tsx
apps/builder/components/shared/buttons/VariablesButton.tsx

[SBOT-103](https://octadesk1614602251.atlassian.net/browse/SBOT-103).
[SBOT-103]: https://octadesk1614602251.atlassian.net/browse/SBOT-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

makes selects reponsives

---

apps/builder/components/shared/Graph/Nodes/StepNode/StepNode/StepNode.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/TextBubbleEditor/TextBubbleEditor.tsx

fix: sets position as absolute when inside card without dialog

---

apps/builder/components/shared/buttons/UploadButton.tsx

fix: changes infos about extensions upload

---

apps/builder/services/graph.ts

Consult [this](https://www.notion.so/octatech/Conven-o-de-Commits-6e9ddde2c4e44cdc9c50e7a0ef42b18c#b34b7041baa24ed28d422cb20de9e744) readme and set the correspondent label(s) on PR.
If your fix/feature changed the current expected behavior or the communication with it, explain.

fix: verify items exists

---

apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WithVariableContent.tsx

Consult [this](https://www.notion.so/octatech/Conven-o-de-Commits-6e9ddde2c4e44cdc9c50e7a0ef42b18c#b34b7041baa24ed28d422cb20de9e744) readme and set the correspondent label(s) on PR.
If your fix/feature changed the current expected behavior or the communication with it, explain.

changing variable name from "..." to "não salvar"

---

apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WithVariableContent.tsx
apps/builder/contexts/WorkspaceContext.tsx

When clicking on don't save the answer of a step, it is shown that the answer is being saved in a variable.

fix:186536 save to a variable

---

apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/OctaCommerceBody/OctaCommerceBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/OctaCommerceBody/SelectProducts/SelectProducts.tsx
apps/builder/services/octadesk/commerce/commerce.ts
apps/builder/services/octadesk/commerce/commerce.type.ts

Product limit in the "Send a catalog" step of WhatsBot V1/V2 - Multiple environments

feat: infinite scroll

---

apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/OfficeHoursBody/OfficeHoursIntervalTimer.tsx

Descreva quais mudanças foram realizadas, como alterações e adições na regra de negócio, novos arquivos e por que.

fix: add 23hrs and 59min on office hours select

---

apps/builder/services/externalEvent.ts

Foi realizado a correção do link da endpoint/api para a montagem da url no componente external-event

fix: Adjust the endpoint url to request the external event url

---

apps/builder/services/externalEvent.ts

Foi feita uma alteração na maneira em que se capta a url do nucleus para montagem da URL

fix: Alternating way to get url for external event

---

.gitignore
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/AssignToTeam/AssignToResponsibleSelect.tsx

add group combination to show selected value

fix: add group combination

---

apps/builder/components/shared/modals/CreateChatFieldModal/CreateChatFieldModal.tsx
apps/builder/contexts/WorkspaceContext.tsx

Descreva quais mudanças foram realizadas, como alterações e adições na regra de negócio, novos arquivos e por que.

Feat: be online: chat fields

---

apps/builder/components/shared/Graph/Edges/Edges.tsx
apps/builder/components/shared/Graph/Graph.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WhatsAppBodies/WhatsAppButtonsListSettings/WhatsAppButtonsListSettingsBody.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/WhatsAppBodies/WhatsAppOptionsListSettings/WhatsAppOptionsListSettingsBody.tsx

https://octadesk1614602251.atlassian.net/browse/CBM-1679

feat: cbm 1673 performance

---

apps/builder/contexts/WorkspaceContext.tsx

Descreva quais mudanças foram realizadas, como alterações e adições na regra de negócio, novos arquivos e por que.

refactor: fix not bringing all variables

---

apps/builder/components/shared/modals/CreateChatFieldModal/CreateChatFieldModal.tsx
apps/builder/helpers/block-connections.ts

Altera o payload do chat custom field para o novo padrão, permitindo que ele seja criado 'enabled'
Testado localmente e deployado em QA

Feat/be online/beta/variable payload

---

apps/builder/components/shared/Graph/Graph.tsx
apps/builder/components/shared/Graph/Nodes/BlockNode/BlockNode.tsx

only hides edges when clicking on board or card

fix: only hides edges when clicking on board or card

---

apps/builder/components/shared/Graph/Nodes/StepNode/StepNodeContent/contents/WithVariableContent.tsx

Reverts Octadesk-Tech/chat-bot-builder-client#162

Revert "fix: when variableid is not found in variables the field has to show ..."

---

apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/InputSettingsBody.tsx

Reverts Octadesk-Tech/chat-bot-builder-client#150

Revert "fix: was fixed select variable unefined"

---

apps/builder/contexts/WorkspaceContext.tsx
apps/builder/enums/customFieldsEnum.ts

[Conversas/Helpdesk] Campos aparecerem dentro do Bot
Esconder as variáveis de multi nivel do tipo 29

feat: exclude field list level in bot select variable

---

apps/builder/components/shared/Graph/Nodes/helpers/helpers.tsx

Adicionamos validação no campo de office hours do build client
Incidente ou Problema #[ (ID do jira, ticket ou servicenow)](https://octadesk1614602251.atlassian.net/jira/software/c/projects/KSC/boards/247?assignee=712020%3Ab8d4ae6f-9d23-4f55-9202-5b02b9785bdd&selectedIssue=KSC-286)
- Adicionamos um bloco de data sem data e validamos se a borda ficou vermelha

feat: was added validation in office hours node

---

Dockerfile_old
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/AssignToTeam/AssignToResponsibleSelect.tsx
build/Dockerfile

add validation before calling function

fix: add validation before calling function

---

apps/builder/components/shared/Graph/Nodes/ItemNode/ItemNodeContent/contents/ConditionNodeContent.tsx
apps/builder/components/shared/Graph/Nodes/StepNode/SettingsPopoverContent/bodies/ConditionSettingsBody/ComparisonsItem.tsx

O campo de Contato chamado "Status do contato" está abrindo uma lista em branco e não esta mostrando as opções
https://octadesk1614602251.atlassian.net/browse/KSC-736

fix: contact field named status do contato not displaying

---

apps/builder/pages/typebots/[typebotId]/edit.tsx

Descreva quais mudanças foram realizadas, como alterações e adições na regra de negócio, novos arquivos e por que.

fix: cursor alert

---

apps/builder/components/shared/Graph/Edges/Edge.tsx
apps/builder/components/shared/Graph/Edges/Edges.tsx
apps/builder/components/shared/Graph/GraphContent.tsx
apps/builder/services/graph.ts

Reduz o número de blocos considerados "visíveis" e garante que as conexões estão aparecendo corretamente.
Issue [#KSC-864](https://octadesk1614602251.atlassian.net/browse/KSC-864)
Tentar editar um fluxo com muitos blocos e conexões.

fix: slowness in editing bots
